
- name: turn off swap
  shell: swapoff -a && sysctl -w vm.swappiness=0

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: update kernel settings
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: stop services
  service:
    name: '{{ item }}'
    state: stopped
  with_items:
    - docker
    - kubelet

- name: create /etc/docker fold if not existed
  file: dest=/etc/docker state=directory mode=755

- name: upload daemon.json for docker
  copy:
    src: daemon.json
    dest: /etc/docker

- name: 'create /etc/docker/certs.d/{{ k8s_image_repo | dirname }} fold if not existed'
  file: dest=/etc/docker/certs.d/{{ k8s_image_repo | dirname }} state=directory mode=755

- name: 'copy CA certificate into /etc/docker/certs.d/{{ k8s_image_repo }}'
  copy:
    src: root_ca.crt
    dest: /etc/docker/certs.d/{{ k8s_image_repo | dirname }}/ca.crt

- name: enable services
  service:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - docker
    - kubelet

- name: start services
  service:
    name: '{{ item }}'
    daemon_reload: yes
    state: started
  with_items:
    - docker
    - kubelet
