---

- name: create {{ k8s_install_root }} directory if not existed
  file: dest={{ k8s_install_root }} state=directory mode=755

- name: '{{ inventory_hostname }} join into cluster as worker'
  shell: '{{hostvars[groups["master"][0]]["worker_join_command"]}} > {{ k8s_install_root }}/kubeadm-join.out'

- name: setup node as worker
  set_fact:
    k8s_mode: worker
