---

- name: create {{ k8s_install_root }} directory if not existed
  file: dest={{ k8s_install_root }} state=directory mode=755

- name: upload node status check tool
  copy:
    src: '{{ playbook_dir }}/files/utils/node_wait.ksh'
    dest: '{{ k8s_install_root }}'
    mode: '0755'

- name: create dir if not existed
  file:
    path: '{{ item | dirname }}'
    state: directory
    mode: 755
  with_items: '{{ master_join_files }}'

- name: upload master join required configuration files
  copy:
    src: '{{ k8s_install_root }}/k8s/{{ groups["master"][0] }}/{{ item }}'
    dest: '{{ item | dirname }}'
  with_items: '{{ master_join_files }}'

- name: '{{ inventory_hostname }} join into cluster as master'
  shell: '{{hostvars[groups["master"][0]]["master_join_command"]}} > {{ k8s_install_root }}/kubeadm-join.out'

- name: setup node as master
  set_fact:
    k8s_mode: master

- import_tasks: '{{ playbook_dir }}/tasks/common/kubectl_cli_conf.yml'

- name: get current master nodes count
  vars:
    master: '{% for h in groups.all %}{% if hostvars[h].k8s_mode is defined %}{% if hostvars[h].k8s_mode == "master" %}{{ h }} {% endif %}{% endif %}{% endfor %}'
  set_fact:
    k8s_master_count: '{{ master.split() | length }}'
